# Generated by Django 5.1 on 2025-02-05 04:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductAvailabilityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="storedproduct",
            name="condition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="storedproduct",
            name="discount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="storedproduct",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="storedproduct",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="storedproduct",
            name="review_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storedproduct",
            name="shipping_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="storedproduct",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="storedproduct",
            name="image_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="storedproduct",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="storedproduct",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="storedproduct",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="storedproduct",
            name="url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AddIndex(
            model_name="storedproduct",
            index=models.Index(
                fields=["product_id", "retailer"], name="products_st_product_f4f82c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedproduct",
            index=models.Index(
                fields=["timestamp"], name="products_st_timesta_f65493_idx"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="products.storedproduct",
            ),
        ),
        migrations.AddField(
            model_name="productavailabilitylog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_logs",
                to="products.storedproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["product", "timestamp"], name="products_pr_product_d7d261_idx"
            ),
        ),
    ]
