# Generated by Django 5.1 on 2024-09-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
