# Generated by Django 5.1 on 2024-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
