# Generated by Django 5.1 on 2024-10-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delapp", "0002_alter_customuser_first_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Waitlist",
        ),
        migrations.AddField(
            model_name="customuser",
            name="lemonsqueezy_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
