# Generated by Django 5.1 on 2024-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delapp", "0003_delete_waitlist_customuser_lemonsqueezy_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="variant_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
