# Generated by Django 5.1 on 2024-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delapp", "0004_usersubscription_variant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="verification_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
