# Generated by Django 5.1 on 2024-10-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delapp", "0006_customuser_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_token_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
