# Generated by Django 5.1 on 2025-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delapp", "0010_conversation_conversationmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmessage",
            name="query_understanding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
