# Generated by Django 5.1 on 2025-04-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delapp', '0011_conversationmessage_query_understanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_products', models.JSONField(default=list)),
                ('last_query', models.TextField(blank=True)),
                ('last_category', models.CharField(blank=True, max_length=100)),
                ('applied_filters', models.JSONField(default=dict)),
                ('last_intent', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation_turn', models.IntegerField(default=0)),
                ('product_references', models.JSONField(default=dict)),
                ('user_preferences', models.JSONField(default=dict)),
                ('keywords', models.JSONField(default=list)),
                ('last_action', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='delapp.conversation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
